### ISSUE TITLE
SFTPStorage backend is not resilient in the face of dropped SSH connections

### ISSUE THREAD

**Issue by pansapiens** [MonashBioinformaticsPlatform/laxy#52]
We frequently see issues relating to SSH-related exceptions from the `SFTPStorage` backend.
(`storages.backends.sftpstorage.SFTPStorage` from `django-storages`). Any time a file with location `laxy+sftp://` is read via the `File.file` file-like handle, we are at risk of bubbling up any of `SSHException`, `AuthenticationException`, `OSError` or `IOError`. In the case of the  `SFTPStorage` backend these are often temporary failures that should be transparently retried.

There are various places where the `backoff` decorator is already used to try and circumvent this, however `SSHException`s keep cropping up. We need to push the `backoff` retries a low level as possible - probably by subclassing/forking `SFTPStorage` to use (configurable ?) `backoff`. Alternatively, use it inside `File.file` when grabbing the file-like - this would probably require wrapping the `SFTPStorageFile` instance in some kind of buffering wrapper that supports `peek` or `seek` (eg `io.BufferedReader`), reading the first byte via `bufferedfile.peek(1)` (since exceptions don't tend to occur until we attempt to read), before returning the bufferedfile.

Another general observation is that using the `SFTPStorage` backend for user-facing file delivery has been generally unreliable in practise (probably very dependent on the particular SFTP host) - better to use other storage backends for this where possible (eg Object Store / S3).

----
As an example of where `SSHException` is often raised:

If the SFTP connection drops or has a timeout during the `expire_old_jobs` Celery task, the task fails to complete and we get this trackback.

```python
Traceback (most recent call last):
  File "/app/laxy_backend/tasks/job.py", line 661, in expire_old_job
    if file_should_be_deleted(f):
  File "/app/laxy_backend/tasks/job.py", line 602, in file_should_be_deleted
    is_large_file = (ff.size / MB) > max_size
  File "/app/laxy_backend/models.py", line 1030, in size
    if size is None and hasattr(self.file, 'size'):
  File "/usr/local/lib/python3.6/site-packages/storages/backends/sftpstorage.py", line 205, in size
    self._size = self._storage.size(self.name)
  File "/usr/local/lib/python3.6/site-packages/storages/backends/sftpstorage.py", line 175, in size
    return self.sftp.stat(remote_path).st_size
  File "/usr/local/lib/python3.6/site-packages/paramiko/sftp_client.py", line 493, in stat
    t, msg = self._request(CMD_STAT, path)
  File "/usr/local/lib/python3.6/site-packages/paramiko/sftp_client.py", line 813, in _request
    return self._read_response(num)
  File "/usr/local/lib/python3.6/site-packages/paramiko/sftp_client.py", line 845, in _read_response
    raise SSHException("Server connection dropped: {}".format(e))
paramiko.ssh_exception.SSHException: Server connection dropped: 
```

The Celery task does appear to get retried automatically after failure - we should probably also catch some temporary exceptions on Celery tasks like this and automatically retry a number of times.

**Comment by pansapiens** [comment]
Closing, since this issue has mostly been solved / worked around.

We are using a [django-storages fork](https://github.com/pansapiens/django-storages) (maybe PRed one day) with a better `SFTPStorage` implementation. 

We [list the backend server twice in the nginx reverse proxy config](https://github.com/MonashBioinformaticsPlatform/laxy/blob/2631f3d70c76bb6e0dd73ca5c82851a6f4deeb41/docker/laxy-static-nginx/nginx.conf.template#L100) - this is a bit of a hack but essentially retries once if the backend returns an error status, mitigating most of the dropped SSH connection issues we were seeing.
