### ISSUE TITLE
Local aria2c can become unresponsive, failing to download input files doesn't immediately fail job

### ISSUE THREAD

**Issue by pansapiens** [MonashBioinformaticsPlatform/laxy#6]
In some cases the local aria2c daemon can become unresponsive (unclear why in this case - can't easily replicate). One case could be if the aria2c daemon was killed ungracefully (reboot) and there is a stale `.aria2_rpc_secret` hanging around.

Example:

```python
+ laxydl download -vvv --cache-path /scratch/df22/andrewpe/laxytest/7bCKe46HzgAnPJ5P7kZeX1/../cache --no-progress --untar --parallel-downloads 8 --event-notification-url http://dev-api.laxy.io:8001/api/v1/job/7bCKe46HzgAnPJ5P7kZeX1/event/ --event-notification-auth-file /scratch/df22/andrewpe/laxytest/7bCKe46HzgAnPJ5P7kZeX1/.private_request_headers --pipeline-config /scratch/df22/andrewpe/laxytest/7bCKe46HzgAnPJ5P7kZeX1/input/pipeline_config.json --destination-path /scratch/df22/andrewpe/laxytest/7bCKe46HzgAnPJ5P7kZeX1/input
INFO: 2018-10-28 17:34:45,651 -- aria2 RPC server is started.
Traceback (most recent call last):
  File "/scratch/df22/andrewpe/laxytest/miniconda3/envs/rnasik-1.5.2/bin/laxydl", line 11, in <module>
    load_entry_point('laxy-downloader', 'console_scripts', 'laxydl')()
  File "/scratch/df22/andrewpe/laxytest/2UcGgfbsA1GPvtFsGoGIVB/src/laxy-downloader/laxy_downloader/downloader/cli.py", line 268, in main
    _run_download_cli(args, rpc_secret)
  File "/scratch/df22/andrewpe/laxytest/2UcGgfbsA1GPvtFsGoGIVB/src/laxy-downloader/laxy_downloader/downloader/cli.py", line 131, in _run_download_cli
    aria.log_status()
  File "/scratch/df22/andrewpe/laxytest/2UcGgfbsA1GPvtFsGoGIVB/src/laxy-downloader/laxy_downloader/downloader/aria.py", line 100, in log_status
    statuses = aria.tellActive() + aria.tellWaiting(0, 999) + aria.tellStopped(0, 999)
  File "/scratch/df22/andrewpe/laxytest/miniconda3/envs/rnasik-1.5.2/lib/python3.6/site-packages/pyaria2/pyaria2.py", line 595, in tellActive
    return self.server.aria2.tellActive("token:" + self.rpcSecret, keys)
  File "/scratch/df22/andrewpe/laxytest/miniconda3/envs/rnasik-1.5.2/lib/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/scratch/df22/andrewpe/laxytest/miniconda3/envs/rnasik-1.5.2/lib/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/scratch/df22/andrewpe/laxytest/miniconda3/envs/rnasik-1.5.2/lib/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/scratch/df22/andrewpe/laxytest/miniconda3/envs/rnasik-1.5.2/lib/python3.6/xmlrpc/client.py", line 1166, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/scratch/df22/andrewpe/laxytest/miniconda3/envs/rnasik-1.5.2/lib/python3.6/xmlrpc/client.py", line 1279, in send_request
    self.send_content(connection, request_body)
  File "/scratch/df22/andrewpe/laxytest/miniconda3/envs/rnasik-1.5.2/lib/python3.6/xmlrpc/client.py", line 1309, in send_content
    connection.endheaders(request_body)
  File "/scratch/df22/andrewpe/laxytest/miniconda3/envs/rnasik-1.5.2/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/scratch/df22/andrewpe/laxytest/miniconda3/envs/rnasik-1.5.2/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/scratch/df22/andrewpe/laxytest/miniconda3/envs/rnasik-1.5.2/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/scratch/df22/andrewpe/laxytest/miniconda3/envs/rnasik-1.5.2/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/scratch/df22/andrewpe/laxytest/miniconda3/envs/rnasik-1.5.2/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/scratch/df22/andrewpe/laxytest/miniconda3/envs/rnasik-1.5.2/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

One solution would be to fallback to the non-aria2c, non-cached download option in this case (non-cached so that we don't corrupt in progress downloads if aria2c is still happily running for other jobs).

The second related issue is that `run_job.sh` should immediately fail if `laxydl` fails to download input files, but it currently forges ahead and attempts to run RNAsik anyway. We should fail fast on unrecoverable errors.

**Comment by pansapiens** [comment]
Stale.
