### ISSUE TITLE
Files without a location field are listed

### ISSUE THREAD

**Issue by pansapiens** [MonashBioinformaticsPlatform/laxy#75]
This occurs when a pipeline run is finished and the output files are being indexed (Job is still in a `running` state). Celery task `job.index_remote_files` is pending or running, and some output files may have already be registered via POSTing a `manifest.csv` to the backend.

In this state, a request to list the output `FileSet` (eg `/api/v1/fileset/23ocbZyEt5JoqSKbTTxzTn/`) returns `Files` without a location field set.

In the frontend, files will appear in the output file browser, but clicking on the 'eye' to view them fails (eg calling `/job/4O9AxOIgS4dVPg243xkxZy/files/output/RNAsik.bds.20190814_121818_512.report.html` returns status `500`).

We should one or several of:

* By default, don't return Files without a location when calling `/api/v1/fileset/{fileset_id}` (possibly allow override to list everything using a query string filter)
* If a File has no location, don't show the view/download actions in the UI.
* Don't list output files for the job until it's completely finished
* REST API should return a nicer status code (404) and message if Files without location are attempted to be accessed
* POSTing `manifest.csv` should automatically set the location field, or allow it to be specified in `manifest.csv` ? (eg in `JobFileBulkRegistration` view)

We could also consider disallowing Files with a blank location (Django model / database constraint). I believe this inflexibility might make some existing processes awkward, however (eg, `manifest.csv` registration).

-----
Example traceback:

```
Attempting view in browser of 7KSDeA1pfbIicO66nMzT5Z
File 7KSDeA1pfbIicO66nMzT5Z location is empty. This isn't allowed and shouldn't ever happen.
[2019-08-14 02:28:14 +0000] [31] [ERROR] Error handling request /api/v1/job/4O9AxOIgS4dVPg243xkxZy/files/output/RNAsik.bds.20190814_121818_512.report.html
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 114, in handle_request
    for item in respiter:
  File "/app/laxy_backend/views.py", line 276, in render
    for chunk in iterable:
  File "/usr/local/lib/python3.6/wsgiref/util.py", line 30, in __next__
    data = self.filelike.read(self.blksize)
AttributeError: 'NoneType' object has no attribute 'read'
```

**Comment by pansapiens** [comment]
Addressed by 5fef36154c1fa4bb63bd081a7035b117c6bc4227 , 3c27ef4c1d730342a26c0683fd94c2ddcb40c908 and 9543952e7f11a59cdcce0764ebf80c09cbb4f029 .
